--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHECKBOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CHECKBOARD" 
   (	"CODENUM" NUMBER(10,0), 
	"STARTDATE" VARCHAR2(30 BYTE), 
	"ENDDATE" VARCHAR2(30 BYTE), 
	"USERSTARTDATE" VARCHAR2(30 BYTE), 
	"USERENDDATE" VARCHAR2(30 BYTE), 
	"RESISTER" VARCHAR2(25 BYTE), 
	"RENTTER" VARCHAR2(25 BYTE), 
	"BILL" NUMBER(15,0), 
	"DEPOSIT" NUMBER(15,0), 
	"PACKAGESTATUS" VARCHAR2(20 BYTE) DEFAULT '대여가능'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007275
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007275" ON "SYSTEM"."CHECKBOARD" ("CODENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CHECKBOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHECKBOARD" ADD PRIMARY KEY ("CODENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CHECKBOARD" MODIFY ("RESISTER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CHECKBOARD" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CHECKBOARD" MODIFY ("STARTDATE" NOT NULL ENABLE);
