--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FREEBOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FREEBOARD" 
   (	"BNUM" NUMBER(10,0), 
	"BGNUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"BDATE" DATE, 
	"CONTENTS" VARCHAR2(2000 BYTE), 
	"READCOUNT" NUMBER(3,0) DEFAULT 0, 
	"GROUPNUM" NUMBER(10,0), 
	"RANKNUM" NUMBER(10,0), 
	"ID" VARCHAR2(25 BYTE), 
	"IMG" VARCHAR2(1000 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREEBOARD4
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FREEBOARD4" 
   (	"BNUM" NUMBER(10,0), 
	"BGNUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"BDATE" DATE, 
	"CONTENTS" VARCHAR2(2000 BYTE), 
	"GROUPNUM" NUMBER(10,0), 
	"RANKNUM" NUMBER(10,0), 
	"ID" VARCHAR2(25 BYTE), 
	"IMG" VARCHAR2(1000 BYTE), 
	"COUNT" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007405
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007405" ON "SYSTEM"."FREEBOARD" ("BNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007410
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007410" ON "SYSTEM"."FREEBOARD4" ("BNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FREEBOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FREEBOARD" ADD PRIMARY KEY ("BNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FREEBOARD" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FREEBOARD" MODIFY ("BDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREEBOARD4
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FREEBOARD4" ADD PRIMARY KEY ("BNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FREEBOARD4" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FREEBOARD4" MODIFY ("BDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FREEBOARD4" MODIFY ("TITLE" NOT NULL ENABLE);
