--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QABOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."QABOARD" 
   (	"BNUM" NUMBER(10,0), 
	"BGNUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"BDATE" DATE, 
	"CONTENTS" VARCHAR2(3000 BYTE), 
	"ID" VARCHAR2(25 BYTE), 
	"IMG" VARCHAR2(1000 BYTE), 
	"COUNT" NUMBER(10,0), 
	"CATEGORY" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007414
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007414" ON "SYSTEM"."QABOARD" ("BNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QABOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."QABOARD" ADD PRIMARY KEY ("BNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."QABOARD" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."QABOARD" MODIFY ("BDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."QABOARD" MODIFY ("TITLE" NOT NULL ENABLE);
