--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REQUESTBOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REQUESTBOARD" 
   (	"CODENUM" NUMBER(10,0), 
	"CATEGORY" VARCHAR2(15 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"STARTDATE" VARCHAR2(30 BYTE), 
	"ENDDATE" VARCHAR2(30 BYTE), 
	"CONTENTS" VARCHAR2(2000 BYTE), 
	"BILL" NUMBER(15,0), 
	"DEPOSIT" NUMBER(15,0), 
	"IMG" VARCHAR2(2000 BYTE), 
	"PACKAGESTATUS" VARCHAR2(20 BYTE) DEFAULT '심사중', 
	"REAQUESTID" VARCHAR2(25 BYTE), 
	"COMPANY" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007428
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007428" ON "SYSTEM"."REQUESTBOARD" ("CODENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REQUESTBOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REQUESTBOARD" ADD PRIMARY KEY ("CODENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."REQUESTBOARD" MODIFY ("REAQUESTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REQUESTBOARD" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REQUESTBOARD" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REQUESTBOARD" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REQUESTBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REQUESTBOARD" MODIFY ("CATEGORY" NOT NULL ENABLE);
