--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RPBOARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RPBOARD" 
   (	"SEQNUM" NUMBER(10,0), 
	"CODENUM" NUMBER(10,0), 
	"STARTDATE" VARCHAR2(30 BYTE), 
	"ENDDATE" VARCHAR2(30 BYTE), 
	"USERSTARTDATE" VARCHAR2(30 BYTE), 
	"USERENDDATE" VARCHAR2(30 BYTE), 
	"CONTENTS" VARCHAR2(2000 BYTE), 
	"BILL" NUMBER(15,0), 
	"ADRESS" VARCHAR2(200 BYTE), 
	"SPOTNUM" VARCHAR2(150 BYTE), 
	"PACKAGESTATUS" VARCHAR2(20 BYTE) DEFAULT '허가대기', 
	"REAQUESTID" VARCHAR2(25 BYTE), 
	"REGISTERID" VARCHAR2(25 BYTE), 
	"COMPANY" VARCHAR2(20 BYTE), 
	"REGISTERDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007402
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007402" ON "SYSTEM"."RPBOARD" ("SEQNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RPBOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RPBOARD" ADD PRIMARY KEY ("SEQNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RPBOARD" MODIFY ("REGISTERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RPBOARD" MODIFY ("REAQUESTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RPBOARD" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RPBOARD" MODIFY ("USERENDDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RPBOARD" MODIFY ("USERSTARTDATE" NOT NULL ENABLE);
